language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install py3compat
  - python setup.py install
# command to run tests
script: nosetests tests
